$ANSIBLE_VAULT;1.1;AES256
62616266636435323237356136356263386463613537393034383334333133373264366363316432
3165373331376336623865386137366134313133623733660a613432323138346432616630666630
32323263346637386331393861383837656166336336316366343539313361663766343964356364