- name: message-1
  ansible.builtin.debug:
    msg: "Hii from msg-1"
  
- name: message-2
  ansible.builtin.debug:
    msg: "Hii from msg-2"

- name: message-3
  ansible.builtin.debug:
    msg: "Hii from msg-3"